repo_url: https://github.com/CubeyTheCube/scratchclient
repo_name: CubeyTheCube/scratchclient
theme:
  name: material
  palette:
    primary: blue
  features:
    - navigation.instant
  icon:
    repo: fontawesome/brands/git-alt
    
plugins:
  - search
